#!/usr/bin/python

import matplotlib.pyplot as plt
import sys
import re
import getopt

marker = '.'
opts, args = getopt.getopt(sys.argv[1:], 'l:S')
for o, a in opts:
  if o == '-l':
    marker = '.-'
  elif o == '-S':
    plt.gca().set_aspect(1.0)

x = []
y = []   
for line in sys.stdin:
  line = line.strip()
  vals = re.split(r'\s+|\s*,\s*', line)
  x.append(vals[0])
  y.append(vals[1])
plt.plot(x, y, marker)
plt.minorticks_on()
plt.grid(which='both', color='#aaaaaa')
# add a little bit of margin around the figure so that minimal/maximal points are easier to see
plt.margins(0.05)
plt.savefig(sys.stdout, format='png')
